version: '3'

services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-dump:/docker-entrypoint-initdb.d

volumes:
  db-data: