# Vector configuration
data_dir = "/tmp"

[sources.scalingo]
type = "http_server"
address = "0.0.0.0:${PORT}"
auth.strategy = "basic"
auth.password = "${LOGDRAIN_USER_PASSWORD}"
auth.username = "${LOGDRAIN_USER_NAME}"
decoding.codec = "vrl"
decoding.vrl.source = ". = parse_key_value!(.message)"

[transforms.access]
type = "remap"
inputs = ["scalingo"]
source = """
.duration = parse_duration!(.duration, "s")
.bytes = to_int!(.bytes)
.status = to_int!(.status)
.ip = del(.from)
.endpoint = del(.path)
.requested_at = del(.timestamp)
del(.container)
del(.protocol)
del(.referer)
del(.request_id)
del(.source_type)
"""

[sinks.timescaledb]
type = "postgres"
inputs = ["access"]
endpoint = "${SCALINGO_POSTGRESQL_URL}"
table = "router"
