export type InconfortThermique = {
  NA5AZ_sum: bigint;
  NA5BE_sum: bigint;
  NA5FZ_sum: bigint;
  NA5GU_sum: bigint;
  NA5OQ_sum: bigint;
  P20_POP80P: number;
  P20_POP80P_PSEUL: number;
  age_bati_19_45: number;
  age_bati_46_90: number;
  age_bati_91_05: number;
  age_bati_post06: number;
  age_bati_pre_19: number;
  clc_1_artificialise: number;
  clc_2_agricole: number;
  clc_3_foret_semiNaturel: number;
  clc_4_humide: number;
  clc_5_eau: number;
  code_commune: string;
  densite_bati: number;
  departement: string;
  epci: string;
  index: number;
  libelle_epci: string;
  libelle_geographique: string;
  over_80_sum_1968: number;
  over_80_sum_1975: number;
  over_80_sum_1982: number;
  over_80_sum_1990: number;
  over_80_sum_1999: number;
  over_80_sum_2009: number;
  over_80_sum_2014: number;
  over_80_sum_2020: number;
  precarite_logement: number;
  region: number;
  s_geom_cstr_bati: number;
  tee_log: number;
  tee_mob: number;
  to_80_sum_1968: number;
  to_80_sum_1975: number;
  to_80_sum_1982: number;
  to_80_sum_1990: number;
  to_80_sum_1999: number;
  to_80_sum_2009: number;
  to_80_sum_2014: number;
  to_80_sum_2020: number;
  under_4_sum_1968: number;
  under_4_sum_1975: number;
  under_4_sum_1982: number;
  under_4_sum_1990: number;
  under_4_sum_1999: number;
  under_4_sum_2009: number;
  under_4_sum_2014: number;
  under_4_sum_2020: number;
};

export type CollectivitesSearchbar = {
  code_commune: string;// | null;
  code_epci: string;// | null;
  libelle_commune: string;// | null;
  libelle_epci: string;// | null;
  search_libelle: string;// | null;
  search_code: string;// | null;
  departement: string;// | null;
  region: string;// | null;
};

export type CarteCommunes = {
  code_commune: string;
  coordinates: string;
  densite_bati: number;
  epci: string;
  geometry: string;
  libelle_commune: string;
  libelle_epci: string;
  precarite_logement: number;
};

export type CLC = {
  centroid: string;
  geometry: string;
  label3: string;
  legend: string;
  pk: number;
  shape_length: number;
};
