export type ConsommationNAFExport = {
  code_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  naf09art10: number;
  art09act10: number;
  art09hab10: number;
  art09mix10: number;
  art09rou10: number;
  art09fer10: number;
  art09inc10: number;
  naf10art11: number;
  art10act11: number;
  art10hab11: number;
  art10mix11: number;
  art10rou11: number;
  art10fer11: number;
  naf11art12: number;
  art11act12: number;
  art11hab12: number;
  art11mix12: number;
  art11rou12: number;
  art11fer12: number;
  art11inc12: number;
  naf12art13: number;
  art12act13: number;
  art12hab13: number;
  art12mix13: number;
  art12rou13: number;
  art12fer13: number;
  art12inc13: number;
  naf13art14: number;
  art13act14: number;
  art13hab14: number;
  art13mix14: number;
  art13rou14: number;
  art13fer14: number;
  art13inc14: number;
  naf14art15: number;
  art14act15: number;
  art14hab15: number;
  art14mix15: number;
  art14rou15: number;
  art14fer15: number;
  art14inc15: number;
  naf15art16: number;
  art15act16: number;
  art15hab16: number;
  art15mix16: number;
  art15rou16: number;
  art15fer16: number;
  art15inc16: number;
  naf16art17: number;
  art16act17: number;
  art16hab17: number;
  art16mix17: number;
  art16rou17: number;
  art16fer17: number;
  art16inc17: number;
  naf17art18: number;
  art17act18: number;
  art17hab18: number;
  art17mix18: number;
  art17rou18: number;
  art17fer18: number;
  art17inc18: number;
  naf18art19: number;
  art18act19: number;
  art18hab19: number;
  art18mix19: number;
  art18rou19: number;
  art18fer19: number;
  art18inc19: number;
  naf19art20: number;
  art19act20: number;
  art19hab20: number;
  art19mix20: number;
  art19rou20: number;
  art19fer20: number;
  art19inc20: number;
  naf20art21: number;
  art20act21: number;
  art20hab21: number;
  art20mix21: number;
  art20rou21: number;
  art20fer21: number;
  art20inc21: number;
  naf21art22: number;
  art21act22: number;
  art21hab22: number;
  art21mix22: number;
  art21rou22: number;
  art21fer22: number;
  art21inc22: number;
  naf22art23: number;
  art22act23: number;
  art22hab23: number;
  art22mix23: number;
  art22rou23: number;
  art22fer23: number;
  art22inc23: number;
  naf09art23: number;
  art09act23: number;
  art09hab23: number;
  art09mix23: number;
  art09inc23: number;
  art09rou23: number;
  art09fer23: number;
  artcom0923: number;
};

export type AOT40Export = {
  nom_site: string;
  type_d_implantation: string;
  valeur_brute: number;
  Latitude: number;
  Longitude: number;
};

export type QualiteSitesBaignadeExport = {
  libelle_geographique: string;
  libelle_departement: string;
  departement: string;
  latitude: number;
  longitude: number;
  point_d_eau: string;
  qualite_eau_2013: string | null;
  qualite_eau_2014: string | null;
  qualite_eau_2015: string | null;
  qualite_eau_2016: string | null;
  qualite_eau_2017: string | null;
  qualite_eau_2018: string | null;
  qualite_eau_2019: string | null;
  qualite_eau_2020: string | null;
  type_d_eau: string | null;
};

export type FeuxForetExport = {
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  region: number;
  nature: string | null;
  annee: number;
  surface_parcourue: number;
  surface_foret: number | null;
  surface_maquis_garrigues: number | null;
  autres_surfaces_naturelles_hors_foret: number | null;
  surfaces_agricoles: number | null;
  surfaces_non_boisees: number | null;
  surfaces_non_boisees_artificialisees: number | null;
  surfaces_non_boisees_naturelles: number | null;
  surface_autres_terres_boisees: number | null;
  autres_surfaces: number | null;
};

export type RGAdbExport = {
  code_geographique: string;
  libelle_geographique: string;
  epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  nb_logement: number;
  nb_logement_alea_moyen_fort: number;
  nb_logement_alea_faible: number;
  nb_logement_sans_alea: number;
  nb_logement_alea_moyen_fort_avant_1920: number;
  nb_logement_alea_moyen_fort_1920_1945: number;
  nb_logement_alea_moyen_fort_1945_1975: number;
  nb_logement_alea_moyen_fort_apres_1975: number;
  nb_logement_alea_faible_avant_1920: number;
  nb_logement_alea_faible_1920_1945: number;
  nb_logement_alea_faible_1945_1975: number;
  nb_logement_alea_faible_apres_1975: number;
  surface_commune: number;
  surface_alea_faible_commune: number;
  surface_alea_moyen_fort_commune: number;
  part_logement_alea_moyen_fort_avant_1920: number;
  part_logement_alea_moyen_fort_1920_1945: number;
  part_logement_alea_moyen_fort_1945_1975: number;
  part_logement_alea_moyen_fort_apres_1975: number;
  part_logement_alea_faible_avant_1920: number;
  part_logement_alea_faible_1920_1945: number;
  part_logement_alea_faible_1945_1975: number;
  part_logement_alea_faible_apres_1975: number;
  part_alea_faible_commune: number;
  part_alea_moyen_fort_commune: number;
};
export type AgricultureBioExport = {
  epci: string;
  libelle_epci: string;
  VARIABLE: string;
  LIBELLE_SOUS_CHAMP: string | null;
  surface_2022: number;
  surface_2021: number;
  surface_2020: number;
  surface_2019: number;
  nombre_2022: number;
  nombre_2021: number;
  nombre_2020: number;
  nombre_2019: number;
};

export type RessourcesEauExport = {
  code_geographique: string;
  libelle_geographique: string;
  code_epci: string;
  libelle_epci: string;
  departement: string;
  libelle_departement: string;
  region: number;
  code_pnr: string | null;
  libelle_pnr: string | null;
  libelle_petr: string | null;
  ept: string | null;
  sous_champ: string;
  libelle_sous_champ: string | null;
  prelevement_2008: number | null;
  prelevement_2009: number | null;
  prelevement_2010: number | null;
  prelevement_2011: number | null;
  prelevement_2012: number | null;
  prelevement_2013: number | null;
  prelevement_2014: number | null;
  prelevement_2015: number | null;
  prelevement_2016: number | null;
  prelevement_2017: number | null;
  prelevement_2018: number | null;
  prelevement_2019: number | null;
  prelevement_2020: number | null;
}

export type EtatCoursDeauExport = {
  etat_cours_d_eau: string | null;
  nom_cours_d_eau: string;
}

// export type SurfacesAgricolesModel = {
//   epci: string;
//   exploitation_sau: number;
//   exploitation_sau_terres_arables: number;
//   exploitation_sau_terres_arables_cereales: number;
//   exploitation_sau_terres_arables_oleagineux: number;
//   exploitation_sau_terres_arables_fourrageres: number;
//   exploitation_sau_terres_arables_tubercules: number;
//   exploitation_sau_terres_arables_legumes_melons_fraises: number;
//   exploitation_sau_terres_arables_fleurs: number;
//   exploitation_sau_terres_arables_autres: number;
//   exploitation_sau_cultures_permanentes: number;
//   exploitation_sau_cultures_permanentes_vigne: number;
//   exploitation_sau_cultures_permanentes_fruits: number;
//   exploitation_sau_cultures_permanentes_autres: number;
//   exploitation_sau_herbe: number;
//   exploitation_sau_herbe_prairies_productives: number;
//   exploitation_sau_herbe_prairies_peu_productives: number;
//   exploitation_sau_subventions: number;
//   exploitation_sau_bois_patures: number;
//   exploitation_sau_jardins: number;
//   superficie_sau: number;
//   superficie_sau_terres_arables: number;
//   superficie_sau_terres_arables_cereales: number;
//   superficie_sau_terres_arables_oleagineux: number;
//   superficie_sau_terres_arables_fourrageres: number;
//   superficie_sau_terres_arables_tubercules: number;
//   superficie_sau_terres_arables_legumes_melons_fraises: number;
//   superficie_sau_terres_arables_fleurs: number;
//   superficie_sau_terres_arables_autres: number;
//   superficie_sau_cultures_permanentes: number;
//   superficie_sau_cultures_permanentes_vigne: number;
//   superficie_sau_cultures_permanentes_fruits: number;
//   superficie_sau_cultures_permanentes_autres: number;
//   superficie_sau_herbe: number;
//   superficie_sau_herbe_prairies_productives: number;
//   superficie_sau_herbe_prairies_peu_productives: number;
//   superficie_sau_subventions: number;
//   superficie_sau_bois_patures: number;
//   superficie_sau_jardins: number;
// }
