export type ConsommationNAFExport = {
  code_geographique: string;
  libelle_geographique: string;
  code_epci: string;
  libelle_epci: string;
  code_departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  naf09art10: number;
  art09act10: number;
  art09hab10: number;
  art09mix10: number;
  art09rou10: number;
  art09fer10: number;
  art09inc10: number;
  naf10art11: number;
  art10act11: number;
  art10hab11: number;
  art10mix11: number;
  art10rou11: number;
  art10fer11: number;
  naf11art12: number;
  art11act12: number;
  art11hab12: number;
  art11mix12: number;
  art11rou12: number;
  art11fer12: number;
  art11inc12: number;
  naf12art13: number;
  art12act13: number;
  art12hab13: number;
  art12mix13: number;
  art12rou13: number;
  art12fer13: number;
  art12inc13: number;
  naf13art14: number;
  art13act14: number;
  art13hab14: number;
  art13mix14: number;
  art13rou14: number;
  art13fer14: number;
  art13inc14: number;
  naf14art15: number;
  art14act15: number;
  art14hab15: number;
  art14mix15: number;
  art14rou15: number;
  art14fer15: number;
  art14inc15: number;
  naf15art16: number;
  art15act16: number;
  art15hab16: number;
  art15mix16: number;
  art15rou16: number;
  art15fer16: number;
  art15inc16: number;
  naf16art17: number;
  art16act17: number;
  art16hab17: number;
  art16mix17: number;
  art16rou17: number;
  art16fer17: number;
  art16inc17: number;
  naf17art18: number;
  art17act18: number;
  art17hab18: number;
  art17mix18: number;
  art17rou18: number;
  art17fer18: number;
  art17inc18: number;
  naf18art19: number;
  art18act19: number;
  art18hab19: number;
  art18mix19: number;
  art18rou19: number;
  art18fer19: number;
  art18inc19: number;
  naf19art20: number;
  art19act20: number;
  art19hab20: number;
  art19mix20: number;
  art19rou20: number;
  art19fer20: number;
  art19inc20: number;
  naf20art21: number;
  art20act21: number;
  art20hab21: number;
  art20mix21: number;
  art20rou21: number;
  art20fer21: number;
  art20inc21: number;
  naf21art22: number;
  art21act22: number;
  art21hab22: number;
  art21mix22: number;
  art21rou22: number;
  art21fer22: number;
  art21inc22: number;
  naf22art23: number;
  art22act23: number;
  art22hab23: number;
  art22mix23: number;
  art22rou23: number;
  art22fer23: number;
  art22inc23: number;
  naf09art23: number;
  art09act23: number;
  art09hab23: number;
  art09mix23: number;
  art09inc23: number;
  art09rou23: number;
  art09fer23: number;
  artcom0923: number;
};

export type AgricultureBioExport = {
  code_epci: string;
  libelle_epci: string;
  variable: string;
  sous_champ: string | null;
  surface_2022_ha: number;
  surface_2021_ha: number;
  surface_2020_ha: number;
  surface_2019_ha: number;
  nombre_exploitations_2022: number;
  nombre_exploitations_2021: number;
  nombre_exploitations_2020: number;
  nombre_exploitations_2019: number;
};

export type ArreteCatNatExport = {
  libelle_risque: string;
  date_publication_arrete: string;
  code_geographique: string;
  code_departement: string;
  libelle_departement: string;
  code_epci: string;
  libelle_epci: string;
  libelle_geographique: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
};

export type IncendiesForetExport = {
  code_geographique: string;
  libelle_geographique: string;
  code_epci: string;
  libelle_epci: string;
  code_departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  nature: string | null;
  annee: number;
  surface_parcourue_km2: number;
  surface_foret_km2: number | null;
  surface_maquis_garrigues_km2: number | null;
  autres_surfaces_naturelles_hors_foret_km2: number | null;
  surfaces_agricoles_km2: number | null;
  surfaces_non_boisees_km2: number | null;
  surfaces_non_boisees_artificialisees_km2: number | null;
  surfaces_non_boisees_naturelles_km2: number | null;
  surface_autres_terres_boisees_km2: number | null;
  autres_surfaces_km2: number | null;
};

export type RGAdbExport = {
  code_geographique: string;
  libelle_geographique: string;
  code_epci: string;
  libelle_epci: string;
  code_departement: string;
  libelle_departement: string;
  region: number;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  nb_logement: number;
  nb_logement_alea_moyen_fort: number;
  nb_logement_alea_faible: number;
  nb_logement_sans_alea: number;
  nb_logement_alea_moyen_fort_avant_1920: number;
  nb_logement_alea_moyen_fort_1920_1945: number;
  nb_logement_alea_moyen_fort_1945_1975: number;
  nb_logement_alea_moyen_fort_apres_1975: number;
  nb_logement_alea_faible_avant_1920: number;
  nb_logement_alea_faible_1920_1945: number;
  nb_logement_alea_faible_1945_1975: number;
  nb_logement_alea_faible_apres_1975: number;
  surface_commune_m2: number;
  surface_alea_faible_commune_m2: number;
  surface_alea_moyen_fort_commune_m2: number;
  part_logement_alea_moyen_fort_avant_1920: number;
  part_logement_alea_moyen_fort_1920_1945: number;
  part_logement_alea_moyen_fort_1945_1975: number;
  part_logement_alea_moyen_fort_apres_1975: number;
  part_logement_alea_faible_avant_1920: number;
  part_logement_alea_faible_1920_1945: number;
  part_logement_alea_faible_1945_1975: number;
  part_logement_alea_faible_apres_1975: number;
  part_alea_faible_commune: number;
  part_alea_moyen_fort_commune: number;
};

export type RessourcesEauExport = {
  libelle_sous_champ: string;
  sous_champ: string;
  code_geographique: string;
  code_departement: string;
  libelle_departement: string;
  code_epci: string;
  libelle_epci: string;
  libelle_geographique: string;
  ept: string | null;
  libelle_petr: string | null;
  code_pnr: string | null;
  libelle_pnr: string | null;
  region: number;
  prelevement_2008_m3: number;
  prelevement_2009_m3: number;
  prelevement_2010_m3: number;
  prelevement_2011_m3: number;
  prelevement_2012_m3: number;
  prelevement_2013_m3: number;
  prelevement_2014_m3: number;
  prelevement_2015_m3: number;
  prelevement_2016_m3: number;
  prelevement_2017_m3: number;
  prelevement_2018_m3: number;
  prelevement_2019_m3: number;
  prelevement_2020_m3: number;
};

export type SurfacesAgricolesExport = {
  code_epci: string;
  exploitation_sau: number;
  exploitation_sau_terres_arables: number;
  exploitation_sau_terres_arables_cereales: number;
  exploitation_sau_terres_arables_oleagineux: number;
  exploitation_sau_terres_arables_fourrageres: number;
  exploitation_sau_terres_arables_tubercules: number;
  exploitation_sau_terres_arables_legumes_melons_fraises: number;
  exploitation_sau_terres_arables_fleurs: number;
  exploitation_sau_terres_arables_autres: number;
  exploitation_sau_cultures_permanentes: number;
  exploitation_sau_cultures_permanentes_vigne: number;
  exploitation_sau_cultures_permanentes_fruits: number;
  exploitation_sau_cultures_permanentes_autres: number;
  exploitation_sau_herbe: number;
  exploitation_sau_herbe_prairies_productives: number;
  exploitation_sau_herbe_prairies_peu_productives: number;
  exploitation_sau_herbe_subventions: number;
  exploitation_sau_herbe_bois_patures: number;
  exploitation_sau_jardins: number;
  superficie_sau_ha: number;
  superficie_sau_terres_arables_ha: number;
  superficie_sau_terres_arables_cereales_ha: number;
  superficie_sau_terres_arables_oleagineux_ha: number;
  superficie_sau_terres_arables_fourrageres_ha: number;
  superficie_sau_terres_arables_tubercules_ha: number;
  superficie_sau_terres_arables_legumes_melons_fraises_ha: number;
  superficie_sau_terres_arables_fleurs_ha: number;
  superficie_sau_terres_arables_autres_ha: number;
  superficie_sau_cultures_permanentes_ha: number;
  superficie_sau_cultures_permanentes_vigne_ha: number;
  superficie_sau_cultures_permanentes_fruits_ha: number;
  superficie_sau_cultures_permanentes_autres_ha: number;
  superficie_sau_herbe_ha: number;
  superficie_sau_herbe_prairies_productives_ha: number;
  superficie_sau_herbe_prairies_peu_productives_ha: number;
  superficie_sau_herbe_subventions_ha: number;
  superficie_sau_herbe_bois_patures_ha: number;
  superficie_sau_jardins_ha: number;
};
